from pathlib import Path
from PIL import Image


def fetch_images_from_local_fs(
    image_urls: list[str],
    imgs_p=Path("../data/unesco_ich/images/thumbs-big/"),
    return_image_objects=False,
    verbose=False,
) -> list[Path | Image.Image]:
    imgs = []
    for img_url in image_urls:
        if "thumbs-big" in str(imgs_p) and "-HUG" in img_url:
            img_url = img_url.replace("-HUG", "-BIG")
        img_fn = imgs_p / Path(img_url).name
        if img_fn.exists():
            try:
                if return_image_objects:
                    img = Image.open(img_fn).convert("RGB")
                    imgs.append(img)
                else:
                    imgs.append(img_fn)
            except (Exception, OSError) as e:
                if verbose:
                    print(f"Error loading {img_fn=} {img_url=}: {e}")
                continue
        else:
            if verbose:
                print(f"Image {img_fn=} {img_url=} not found")
            continue
    return imgs


ICH_REGIONS_TO_COUNTRIES = {
    "Arab States": [
        "Algeria",
        "Tunisia",
        "Saudi Arabia",
        "Yemen",
        "Syria",
        "Egypt",
        "Bahrain",
        "Qatar",
        "Palestine",
        "Sudan",
        "Mauritania",
        "Morocco",
        "Lebanon",
        "Kuwait",
        "Jordan",
        "Iraq",
        "Oman",
        "United Arab Emirates",
    ],
    "Asian and Pacific States": [
        "Afghanistan",
        "Papua New Guinea",
        "Philippines",
        "Timor-Leste",
        "Samoa",
        "Sri Lanka",
        "Bhutan",
        "Kazakhstan",
        "China",
        "Korea",
        "Bangladesh",
        "Cambodia",
        "Cook Islands",
        "Korea",
        "Pakistan",
        "Australia",
        "Tonga",
        "Thailand",
        "Nepal",
        "New Zealand",
        "Fiji",
        "India",
        "Indonesia",
        "Japan",
        "Singapore",
        "Vietnam",
        "Kyrgyzstan",
        "Iran",
        "Lao",
        "Vanuatu",
        "Malaysia",
        "Turkmenistan",
        "Micronesia",
        "Mongolia",
        "Myanmar",
    ],
    "Eastern European States": [
        "Bosnia and Herzegovina",
        "Uzbekistan",
        "Lithuania",
        "Hungary",
        "Croatia",
        "Serbia",
        "Estonia",
        "Georgia",
        "Ukraine",
        "Moldova",
        "Montenegro",
        "Albania",
        "Bulgaria",
        "Slovakia",
        "Poland",
        "Armenia",
        "Belarus",
        "Tajikistan",
        "Azerbaijan",
        "Czechia",
        "Latvia",
        "North Macedonia",
        "Russia",
        "Romania",
        "Slovenia",
    ],
    "Latin-American and Caribbean States": [
        "Argentina",
        "Jamaica",
        "Guatemala",
        "Colombia",
        "Grenada",
        "Saint Vincent and the Grenadines",
        "Curaçao",
        "Chile",
        "Bolivia",
        "Uruguay",
        "Bahamas",
        "Venezuela",
        "Antigua and Barbuda",
        "Haiti",
        "Brazil",
        "Saint Kitts and Nevis",
        "Honduras",
        "Ecuador",
        "El Salvador",
        "Mexico",
        "Dominican Republic",
        "Costa Rica",
        "Paraguay",
        "Panama",
        "Nicaragua",
        "Belize",
        "Cuba",
        "Peru",
    ],
    "Subsaharian African States": [
        "Lesotho",
        "Nigeria",
        "Cameroon",
        "Madagascar",
        "Malawi",
        "Guinea",
        "Ethiopia",
        "Niger",
        "Mauritius",
        "Mali",
        "Djibouti",
        "Côte d'Ivoire",
        "Botswana",
        "Cabo Verde",
        "Eritrea",
        "Burundi",
        "Burkina Faso",
        "Namibia",
        "Central African Republic",
        "Democratic Republic of the Congo",
        "Zimbabwe",
        "Kenya",
        "Angola",
        "Seychelles",
        "Senegal",
        "Togo",
        "Chad",
        "Zambia",
        "Rwanda",
        "Benin",
        "South Africa",
        "Eswatini",
        "Mozambique",
        "South Sudan",
        "Congo",
        "Ghana",
        "Gambia",
        "Gabon",
        "Somalia",
        "Uganda",
    ],
    "Western European and North American States": [
        "Sweden",
        "Canada",
        "Luxembourg",
        "United Kingdom of Great Britain and Northern Ireland",
        "Netherlands",
        "Portugal",
        "Belgium",
        "Switzerland",
        "Malta",
        "Cyprus",
        "France",
        "Iceland",
        "Ireland",
        "Norway",
        "Finland",
        "Spain",
        "Andorra",
        "Türkiye",
        "Denmark",
        "Germany",
        "Greece",
        "Italy",
        "Austria",
    ],
}


ALTERNATIVE_COUNTRY_NAMES = {
    "Australia": "Australia",
    "Benin": "Benin",
    "Nigeria": "Nigeria",
    "Togo": "Togo",
    "Bolivia (Plurinational State of)": "Bolivia",
    "China": "China",
    "Côte d'Ivoire": "Côte d'Ivoire",
    "Dominican Republic": "Dominican Republic",
    "Ecuador": "Ecuador",
    "Peru": "Peru",
    "Georgia": "Georgia",
    "Guinea": "Guinea",
    "India": "India",
    "Italy": "Italy",
    "Papua New Guinea": "Papua New Guinea",
    "Japan": "Japan",
    "Lithuania": "Lithuania",
    "Morocco": "Morocco",
    "Philippines": "Philippines",
    "Republic of Korea": "Korea",
    "Russian Federation": "Russia",
    "Spain": "Spain",
    "Uzbekistan": "Uzbekistan",
    "Belize": "Belize",
    "Guatemala": "Guatemala",
    "Honduras": "Honduras",
    "Nicaragua": "Nicaragua",
    "Azerbaijan": "Azerbaijan",
    "Belgium": "Belgium",
    "Türkiye": "Türkiye",
    "Estonia": "Estonia",
    "Brazil": "Brazil",
    "Colombia": "Colombia",
    "Cuba": "Cuba",
    "Cook Islands": "Cook Islands",
    "Jamaica": "Jamaica",
    "Mexico": "Mexico",
    "Cambodia": "Cambodia",
    "Indonesia": "Indonesia",
    "Kyrgyzstan": "Kyrgyzstan",
    "Mongolia": "Mongolia",
    "Tonga": "Tonga",
    "Vanuatu": "Vanuatu",
    "Viet Nam": "Vietnam",
    "Egypt": "Egypt",
    "Iraq": "Iraq",
    "Yemen": "Yemen",
    "Madagascar": "Madagascar",
    "Central African Republic": "Central African Republic",
    "Latvia": "Latvia",
    "Tajikistan": "Tajikistan",
    "Armenia": "Armenia",
    "Bulgaria": "Bulgaria",
    "Slovakia": "Slovakia",
    "Romania": "Romania",
    "Costa Rica": "Costa Rica",
    "Bangladesh": "Bangladesh",
    "Malawi": "Malawi",
    "Algeria": "Algeria",
    "Jordan": "Jordan",
    "Palestine": "Palestine",
    "Mali": "Mali",
    "Mozambique": "Mozambique",
    "Uganda": "Uganda",
    "Zambia": "Zambia",
    "Gambia": "Gambia",
    "Senegal": "Senegal",
    "Czechia": "Czechia",
    "France": "France",
    "Albania": "Albania",
    "Bhutan": "Bhutan",
    "Malaysia": "Malaysia",
    "Zimbabwe": "Zimbabwe",
    "Hungary": "Hungary",
    "Uruguay": "Uruguay",
    "Chile": "Chile",
    "Croatia": "Croatia",
    "Cyprus": "Cyprus",
    "Argentina": "Argentina",
    "Iran (Islamic Republic of)": "Iran",
    "Belarus": "Belarus",
    "Kenya": "Kenya",
    "Oman": "Oman",
    "Luxembourg": "Luxembourg",
    "United Arab Emirates": "United Arab Emirates",
    "Mauritania": "Mauritania",
    "Portugal": "Portugal",
    "Venezuela (Bolivarian Republic of)": "Venezuela",
    "Austria": "Austria",
    "North Macedonia": "North Macedonia",
    "Botswana": "Botswana",
    "Burkina Faso": "Burkina Faso",
    "Ethiopia": "Ethiopia",
    "Republic of Moldova": "Moldova",
    "Greece": "Greece",
    "Niger": "Niger",
    "Ukraine": "Ukraine",
    "Democratic People's Republic of Korea": "Korea",
    "Burundi": "Burundi",
    "Bosnia and Herzegovina": "Bosnia and Herzegovina",
    "Kazakhstan": "Kazakhstan",
    "Lebanon": "Lebanon",
    "Mauritius": "Mauritius",
    "Serbia": "Serbia",
    "Saudi Arabia": "Saudi Arabia",
    "Turkmenistan": "Turkmenistan",
    "Andorra": "Andorra",
    "Qatar": "Qatar",
    "Namibia": "Namibia",
    "Norway": "Norway",
    "Afghanistan": "Afghanistan",
    "Pakistan": "Pakistan",
    "Germany": "Germany",
    "Switzerland": "Switzerland",
    "Slovenia": "Slovenia",
    "Ireland": "Ireland",
    "Netherlands": "Netherlands",
    "Panama": "Panama",
    "Lao People's Democratic Republic": "Lao",
    "Poland": "Poland",
    "Syrian Arab Republic": "Syria",
    "Sri Lanka": "Sri Lanka",
    "Thailand": "Thailand",
    "Sweden": "Sweden",
    "Tunisia": "Tunisia",
    "Cabo Verde": "Cabo Verde",
    "Samoa": "Samoa",
    "Singapore": "Singapore",
    "Malta": "Malta",
    "Kuwait": "Kuwait",
    "Finland": "Finland",
    "Paraguay": "Paraguay",
    "Denmark": "Denmark",
    "Iceland": "Iceland",
    "Timor-Leste": "Timor-Leste",
    "Seychelles": "Seychelles",
    "Congo": "Congo",
    "Democratic Republic of the Congo": "Democratic Republic of the Congo",
    "Bahrain": "Bahrain",
    "Sudan": "Sudan",
    "Montenegro": "Montenegro",
    "Micronesia (Federated States of)": "Micronesia",
    "Grenada": "Grenada",
    "Cameroon": "Cameroon",
    "Bahamas": "Bahamas",
    "Angola": "Angola",
    "Djibouti": "Djibouti",
}
